# Generated by Django 3.2.9 on 2021-11-22 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Book Title')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('pub_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021)], verbose_name='Publication Year')),
                ('isbn', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(999999999), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='ISBN')),
                ('page_count', models.PositiveIntegerField(verbose_name='Page Count')),
                ('cover_url', models.URLField(default='www.example.com', verbose_name='Cover URL')),
                ('lang', models.CharField(max_length=2, verbose_name='Language')),
            ],
        ),
    ]
