# Generated by Django 3.2.9 on 2021-11-22 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_book_pub_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='lang',
            field=models.CharField(max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(verbose_name='Page Count'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021)], verbose_name='Publication Year'),
        ),
    ]
