# Generated by Django 3.2.9 on 2021-11-22 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20211122_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(999999999), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='ISBN'),
        ),
    ]
