# Generated by Django 3.2.9 on 2021-11-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(default='https://www.example.com', verbose_name='Cover URL'),
        ),
    ]
